### ISSUE TITLE
RSSI

### ISSUE THREAD

**Issue by pitoss** [Cleric-K/FlySky-i6X_Firmware_BugFix#4]
Hello and greetings from Greece.
i saw your bug fix and its awesome,
curently was using a custom firmware that makes rssi osd work on channel 7,8 via the yt video https://www.youtube.com/watch?v=DxnWGq_h21o.

i flashed the bug fix firmware but rssi not working , is it a plan to the future for you to make it happen?

thank you

**Comment by Cleric-K** [comment]
Hi,
I don't have plans for this because there's a better solution:
https://github.com/Cleric-K/FlySkyRxFirmwareRssiMod
It is much better to patch the firmware of the Receiver.
When the transmitter is responsible for RSSI, it receives the RSSI from the RX as telemetry and then sends it back as channel data. This is kinda redundant.
If you patch the RX itself, it simply writes the RSSI to the IBUS frame.

Regards~
